- hosts: localhost
  become: no
  gather_facts: no

  tasks:
    - name: terraform destroy
      shell: >-
        terraform get -update && terraform destroy -force -lock=false
      args:
        chdir: "{{ playbook_dir }}/terraform/{{ layer_name }}"

