---
graylog_appliance_conf:
  - conf_key: "password_secret"
    conf_value: "{{ graylog_server_salt }}"
  - conf_key: "root_password_sha2"
    conf_value: "{{ graylog_admin_password|hash('sha256') }}"
  - conf_key: "web_listen_uri"
    conf_value: "http://{{ ansible_default_ipv4.address }}:9000/"
  - conf_key: "rest_listen_uri"
    conf_value: "http://{{ ansible_default_ipv4.address }}:9000/api/"
  - conf_key: "web_endpoint_uri"
    conf_value: "http://graylog.{{ dns_internal_domain }}/api"
