---
project_region: "{{ my_project_region }}"
entry_domain: "{{ dns_public_domain }}"
vpc_cidr: "10.42.0.0/16"

public_subnet_cidr_a: "10.42.10.0/24"
private_subnet_cidr_a: "10.42.110.0/24"

public_subnet_cidr_b: "10.42.20.0/24"
private_subnet_cidr_b: "10.42.120.0/24"

public_subnet_cidr_c: "10.42.30.0/24"
private_subnet_cidr_c: "10.42.130.0/24"

masters_number: 3

workers_number: 1

logstore_number: 1

monitor_default_public_key: "{{ lookup('file', default_local_public_key_file) }}"

monitor_number: 1

route53_zone_id: "{{ dns_public_zone_id }}"
route53_zone_domain: "{{ dns_public_domain }}"

route53_internal_zone_id: "{{ dns_internal_zone_id }}"
route53_internal_zone_domain: "{{ dns_internal_domain }}"