---
- group:
    name: "{{ statsd_exporter_user }}"
    system: yes

- user:
    name: "{{ statsd_exporter_user }}"
    group: "{{ statsd_exporter_user }}"
    home: "{{ statsd_exporter_deploy_dir }}"
    createhome: no

- get_url:
    url: "{{ statsd_exporter_archive_url }}"
    dest: "{{ ansible_cache_dir }}/{{ statsd_exporter_archive_name }}"
    sha256sum: "{{ statsd_exporter_archive_sum[statsd_exporter_version] }}"

- unarchive:
    src: "{{ ansible_cache_dir }}/{{ statsd_exporter_archive_name }}"
    dest: "{{ statsd_exporter_unarchive_dir }}/"
    owner: "{{ statsd_exporter_user }}"
    group: "{{ statsd_exporter_user }}"
    copy: no

- file:
    src: "{{ statsd_exporter_unarchive_dir }}/statsd_exporter-{{ statsd_exporter_version }}.linux-amd64"
    state: link
    dest: "{{ statsd_exporter_deploy_dir }}"
    owner: "{{ statsd_exporter_user }}"
    group: "{{ statsd_exporter_user }}"

- template:
    src: statsd_exporter.service.j2
    dest: /lib/systemd/system/statsd_exporter.service
  register: statsd_exporter_service

- template:
    src: consul.service.json.j2
    dest: /etc/consul.d/statsd_exporter.json
  notify: restart consul

- shell: >
    systemctl daemon-reload
  when: statsd_exporter_service|changed
  notify: restart statsd_exporter

- service:
    name: statsd_exporter
    state: started
    enabled: yes

- file:
    path: "{{ statsd_exporter_deploy_dir }}/txt"
    state: directory
    owner: "{{ statsd_exporter_user }}"
    group: "{{ statsd_exporter_user }}"

- copy:
    dest: "{{ statsd_exporter_deploy_dir }}/txt/host.prom"
    content: |
      host{hostname="{{ ansible_hostname }}"} 1
    owner: "{{ statsd_exporter_user }}"
    group: "{{ statsd_exporter_user }}"
  notify: restart statsd_exporter

- meta: flush_handlers