---
- name: restart statsd_exporter
  service:
    name: statsd_exporter
    state: restarted
    enabled: yes

- name: restart consul
  service:
    name: consul
    state: restarted
    enabled: yes