---
consul_cache_dir: "/var/cache/ansible"

consul_version: "0.9.2"
consul_archive_sum: "0a2921fc7ca7e4702ef659996476310879e50aeeecb5a205adfdbe7bd8524013"

consul_url_prefix: "https://releases.hashicorp.com/consul/{{ consul_version }}"
consul_archive_name: "consul_{{ consul_version }}_linux_amd64.zip"
consul_archive_dest: "{{ consul_cache_dir }}/{{ consul_archive_name }}"
consul_archive_url: "{{ consul_url_prefix }}/{{ consul_archive_name }}"

consul_data_dir: "/var/lib/consul"
consul_config_dir: "/etc/consul.d"

consul_dc_name: "dc1"

consul_user_name: "consul"
consul_user_id: "801"

consul_network_interface: eth0

consul_mode: "node"

consul_ansible_bootstrap_group: "{{ groups[consul_ansible_bootstrap_group_name] }}"

consul_local_tls_dir: "{{ secrets_dir }}/consul/tls"
consul_local_cluster_encrypt_key: "{{ secrets_dir }}/consul/encrypt.key"

consul_cluster_encrypt_key: >-
  {{ lookup(
       'password',
       consul_local_cluster_encrypt_key + ' chars=ascii_letters,digits,hexdigits,punctuation length=16'
     )
     |b64encode
  }}

consul_ca_data:
  country: "FR"
  state: "IDF"
  locality: "Paris"
  organization: "WeScale"

consul_ca_info:
  C: "FR"
  ST: "IDF"
  L: "Paris"
  O: "WeScale"

consul_root_cert_subj: >-
  {% for key in consul_ca_info %}/{{ key }}={{ consul_ca_info[key] }}{% endfor %}/CN={{ consul_dc_name }}.consul

consul_node_cert_subj: >-
  {% for key in consul_ca_info %}/{{ key }}={{ consul_ca_info[key] }}{% endfor %}/CN={{ inventory_hostname }}.node.{{ consul_dc_name }}.consul

consul_log_dest: "/var/log/consul.log"