---
consul_cache_dir: "/var/cache/run"

consul_version: "0.8.3"
consul_archive_sum: "f894383eee730fcb2c5936748cc019d83b220321efd0e790dae9a3266f5d443a"

consul_url_prefix: "https://releases.hashicorp.com/consul/{{ consul_version }}"
consul_archive_name: "consul_{{ consul_version }}_linux_amd64.zip"
consul_archive_dest: "{{ consul_cache_dir }}/{{ consul_archive_name }}"
consul_archive_url: "{{ consul_url_prefix }}/{{ consul_archive_name }}"

consul_data_dir: "/var/lib/consul"
consul_config_dir: "/etc/consul.d"

consul_dc_name: "dc1"

consul_user_name: "consul"
consul_user_id: "801"

consul_network_interface: eth0

consul_mode: "node"