---
- name: create data directory
  file:
    path: "{{ consul_data_dir }}"
    state: directory
    mode: 0700
    owner: "{{ consul_user_name }}"
    group: "{{ consul_user_name }}"

- name: create configuration directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: "{{ consul_user_name }}"
  with_items:
    - "{{ consul_config_dir }}"
    - "{{ consul_config_dir }}/tls"

- set_fact:
    consul_node_tls_workdir: "{{ consul_local_tls_dir }}/{{ inventory_hostname }}"

- name: local certificates generation
  include: local_ca_certificate.yml
  delegate_to: localhost
  run_once: true
  become: no

- name: certificate upload
  copy:
    src: "{{ consul_local_tls_dir }}/consul-root.cer"
    dest: "{{ consul_config_dir }}/tls/consul-root.cer"

- name: create node cert signing
  shell: >-
    openssl req
    -newkey rsa:4096
    -nodes
    -subj "{{ consul_node_cert_subj }}"
    -out {{ consul_config_dir }}/tls/consul-node.csr
    -keyout {{ consul_config_dir }}/tls/consul-node.key
    && chown root:{{ consul_user_name}} *
    && chmod 640 *
  args:
    warn: no
    chdir: "{{ consul_config_dir }}/tls"
    creates: "{{ consul_config_dir }}/tls/consul-node.csr"

- name: get certificate signing request
  fetch:
    src: "{{ consul_config_dir }}/tls/consul-node.csr"
    dest: "{{ consul_node_tls_workdir }}/consul-node.csr"
    flat: yes

- name: local node certificate generation
  include: local_node_certificate.yml
  delegate_to: localhost
  become: no

- copy:
    src: "{{ consul_node_tls_workdir }}/consul-node.cer"
    dest: "{{ consul_config_dir }}/tls/consul-node.cer"
    owner: root
    group: "{{ consul_user_name }}"
    mode: 0640

- name: generate agent configuration
  template:
    src: "config.json.j2"
    dest: "{{ consul_config_dir }}/config.json"
    owner: root
    group: "{{ consul_user_name }}"
    mode: 0640
    validate: consul validate %s
  notify: restart consul

- name: generate default variables
  template:
    src: "{{ consul_mode }}/defaults.j2"
    dest: "/etc/default/consul"
    group: "{{ consul_user_name }}"
    mode: 0640
  notify: restart consul
