---
- assert:
    that:
      - dns_internal_domain is defined
    msg: "dns_internal_domain var should defined for traefik exposure"

- include: setup_user_and_group.yml

- include: get_consul.yml

- include: configure.yml

- include: sys_integration.yml
