---
- hosts: entry
  become: yes
  roles:
    - role: traefik
      vars:
        traefik_consul_tags:
          - exposed
          - public

- hosts: entry_internal
  become: yes
  roles:
    - role: traefik
      vars:
        traefik_consul_tags:
          - internals
          - monitor
