---
- hosts: all
  become: yes

  pre_tasks:

    - apt_repository:
        repo: "deb http://httpredir.debian.org/debian stretch-backports main contrib non-free"
        update_cache: yes

  roles:
    - unbound
    - consul-agent
#    - prometheus-node


