---
- assert:
    that:
      - graylog_admin_password is defined
      - graylog_server_salt is defined
    msg: >-
      'graylog_server_salt' and 'graylog_admin_password' variables must be defined.

- name: add elasticsearch project repository key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: add elasticsearch project repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    filename: "elastic-5.x"
    update_cache: yes

- name: add graylog project repository
  apt:
    deb: "https://packages.graylog2.org/repo/packages/graylog-2.3-repository_latest.deb"

- apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "ca-certificates-java"
    - "apt-transport-https"
    - "openjdk-8-jre-headless"
    - "uuid-runtime"
    - "pwgen"
    - "mongodb-server"
    - "elasticsearch"
    - "graylog-server"

- name: dedicate elasticsearch instance to graylog
  lineinfile:
    path: "/etc/elasticsearch/elasticsearch.yml"
    regexp: >-
      ^cluster.name: .*$
    line: >-
      cluster.name: graylog
  notify: restart elasticsearch

- name: enable graylog services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "elasticsearch"
    - "graylog-server"

- name: declare graylog webapp to consul
  template:
    src: "graylog.consul-service.json.j2"
    dest: "/etc/consul.d/graylog.consul-service.json"
  notify: restart consul

- name: configure graylog
  lineinfile:
    path: "/etc/graylog/server/server.conf"
    regexp: >-
      ^.*{{ item.conf_key }} =.*$
    line: >-
      {{ item.conf_key }} = {{ item.conf_value }}
  with_items: "{{ graylog_appliance_conf }}"
  notify: restart graylog

- meta: flush_handlers