---
- apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    filename: "elastic-5.x"
    update_cache: yes

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "ca-certificates-java"
    - "apt-transport-https"
    - "openjdk-8-jre-headless"
    - "uuid-runtime"
    - "pwgen"
    - "mongodb-server"
    - "elasticsearch"

- lineinfile:
    path: "/etc/elasticsearch/elasticsearch.yml"
    regexp: >-
      ^cluster.name: .*$
    line: >-
      cluster.name: graylog
  notify: restart elasticsearch

- name: enable elasticsearch
  systemd:
    name: "elasticsearch"
    state: started
    enabled: yes

- name: install graylog project repository
  apt:
    deb: "https://packages.graylog2.org/repo/packages/graylog-2.3-repository_latest.deb"

- apt:
    name: "graylog-server"
    state: present
    update_cache: yes

- set_fact:
    graylog_server_salt: >-
      {{ lookup('password', secrets_dir+'/graylog_server_salt chars=ascii_letters,digits,hexdigits,punctuation length=64') }}
    graylog_admin_password: >-
      {{ lookup('password', secrets_dir+'/graylog_admin_password chars=ascii_letters,digits,hexdigits,punctuation length=64') }}

- name: enable graylog
  systemd:
    name: "graylog-server"
    state: started
    enabled: yes

- template:
    src: "graylog.consul-service.json.j2"
    dest: "/etc/consul.d/graylog.consul-service.json"
  notify: restart consul

- name: configure graylog
  lineinfile:
    path: "/etc/graylog/server/server.conf"
    regexp: >-
      ^.*{{ item.conf_key }} =.*$
    line: >-
      {{ item.conf_key }} = {{ item.conf_value }}
  with_items: "{{ graylog_appliance_conf }}"
  notify: restart graylog
