---
- name: include the necessary coordination step
  include: "{{ playbook_dir }}/inc/team_up.yml"

- name: include the configuration chapters -> {{ item }}
  include: "{{ playbook_dir }}/inc/configure/setup_{{ item }}.yml"
  with_items:
    - all
    - monitor
    - nomad_masters
    - nomad_workers
    - nomad_entry_points
    - nomad_graylog
