---
- include: "{{ playbook_dir }}/inc/team_up.yml"

- include: "{{ playbook_dir }}/inc/configure/setup_all.yml"

- include: "{{ playbook_dir }}/inc/configure/setup_monitor.yml"

- include: "{{ playbook_dir }}/inc/configure/setup_nomad_masters.yml"

- include: "{{ playbook_dir }}/inc/configure/setup_nomad_workers.yml"

- include: "{{ playbook_dir }}/inc/configure/setup_entry_points.yml"

- include: "{{ playbook_dir }}/inc/configure/setup_graylog.yml"