---
- hosts: all
  strategy: free
  become: yes
  pre_tasks:
    - debug: msg={{hostvars[inventory_hostname]}}
  roles:
    - consul-agent
    - unbound
    - prometheus-node

- hosts: monitor
  strategy: free
  become: yes
  roles:
    - prometheus-master
    - grafana

- hosts: nomad-servers-bootstrap
  strategy: free
  become: yes
  roles:
    - nomad-server
    - prometheus-statsd

- hosts: nomad-workers
  strategy: free
  become: yes
  roles:
    - nomad-worker
    - prometheus-statsd
    - docker

- hosts: entry
  strategy: free
  become: yes
  roles:
    - traefik
