---
- hosts: all
  become: yes

  vars:
    consul_acl_master_token: b1gs33cr3t

  tasks:
    - template:
        src: templates/config-acl.json.j2
        dest: /etc/consul.d/config-acl.json
        owner: root
        group: consul
        mode: 0640
      notify: restart consul

    - meta: flush_handlers

    - uri:
        url : "http://127.0.0.1:8500/v1/acl/create"
        return_content: yes
        method: PUT
        headers:
          X-Consul-Token: "{{ consul_acl_master_token }}"
        body_format: json
        body:
          Name: "Agent token"
          Type: "client"
          Rules: >-
            agent "{{ inventory_hostname }}" { policy = "read" }
            node "{{ inventory_hostname }}" { policy = "write" }
            node "" { policy = "read" }
      delegate_to: "{{ groups[consul_ansible_bootstrap_group_name][0] }}"
      register: agent_token

    - debug:
        var: agent_token
      when: consul_acl_agent_token is not defined

    - template:
        src: templates/config-acl.json.j2
        dest: /etc/consul.d/config-acl.json
        owner: root
        group: consul
        mode: 0640
      notify: restart consul

  handlers:
    - name: restart consul
      service:
        name: consul
        state: restarted