---
- hosts: all
  become: yes

  vars:
    consul_acl_master_token: b1gs33cr3t
    consul_acl_agent_token: ee7859ac-2ce8-c4af-427e-0917963bd1f6

  tasks:
    - pip:
        name: "{{ item }}"
      with_items:
        - python-consul
        - pyhcl
      when: >-
        'consul-servers-bootstrap' in group_names

    - service:
        name: consul
        state: restarted

    - template:
        src: templates/config-acl.json.j2
        dest: /etc/consul.d/config-acl.json
        owner: root
        group: consul
        mode: 0640
      notify: restart consul

    - meta: flush_handlers

    - uri:
        url : "http://127.0.0.1:8500/v1/acl/create"
        return_content: yes
        method: PUT
        headers:
          X-Consul-Token: "{{ consul_acl_master_token }}"
        body_format: json
        body:
          Name: "Agent token"
          Type: "client"
          Rules: >-
            agent "" { policy = "read" }
            node "" { policy = "write" }
            service "node" { policy = "write" }
      run_once: true
      delegate_to: masters_0
      register: agent_token
      when: consul_acl_agent_token is not defined

    - debug:
        var: agent_token
      when: consul_acl_agent_token is not defined

  handlers:
    - name: restart consul
      service:
        name: consul
        state: restarted