---
- hosts: localhost
  become: no
  gather_facts: no

  pre_tasks:
    - assert:
        that:
          - layer_name is defined
        msg: >-
          Please define 'layer_name' variable.

  tasks:
    - name: "{{ layer_name }} - terraform plan"
      shell: >-
        terraform init
        &&
        terraform plan {{ common_tf_vars }} -lock=false
      args:
        chdir: "{{ terraform_current_layer }}"
      register: tf_plan
      tags:
        - terraform

    - pause:
        prompt: |-
          ############### READ CAREFULLY !!!
          {{ tf_plan.stdout }}
          ############### READ CAREFULLY !!!

          Type 'apply' if you want this to be done.
      register: prompted
      when: not (auto_apply|default(false))
      tags:
        - terraform

    - meta: end_play
      when:
        - not (auto_apply|default(false))
        - prompted is defined and prompted.user_input != 'apply'
      tags:
        - terraform

    - name: "{{ layer_name }} - terraform apply"
      shell: >-
        terraform apply {{ common_tf_vars }} -lock=false
      args:
        chdir: "{{ terraform_current_layer }}"
      tags:
        - terraform

    - name: "{{ layer_name }} - checking for var file to generate inventory"
      stat:
        path: "{{ terraform_current_layer }}/inventory-map.yml"
      register: inventory_map

    - name: "{{ layer_name }} - generating local inventory"
      include: "{{ playbook_dir }}/inc/generate_tf_layer_inventory.yml"
      when: inventory_map.stat.exists
