---
- name: Ensure optional elasticsearch group is created with the correct id.
  group:
    state: present
    name: "{{ es_group }}"
    system: yes
    gid: "{{ es_group_id }}"

- name: Ensure optional elasticsearch user is created with the correct id.
  user:
    state: present
    name: "{{ es_user }}"
    system: yes
    createhome: no
    uid: "{{ es_user_id }}"
    group: "{{ es_group }}"

- name: Add Elasticsearch repository key
  apt_key:
    url: "{{ es_apt_key }}"
    state: present

- name: Add elasticsearch repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state}}"
  with_items:
    - repo: "{{ es_apt_url_old }}"
      state: "absent"
    - repo: "{{ es_apt_url }}"
      state: "present"


- name: Ensure elasticsearch is installed
  apt:
    name: elasticsearch
    state: present
    force: "{{ force_install }}"
    cache_valid_time: 86400
