---
- include: elasticsearch-parameters.yml

- include: java.yml

- include: elasticsearch.yml
  tags:
    - install

- include: elasticsearch-config.yml
  tags:
    - config

- include: elasticsearch-plugins.yml
  tags:
    - plugins

- meta: flush_handlers

- service:
    name: elasticsearch
    state: started
    enabled: true