---
nomad_server_cache_dir: "/var/cache/run"

nomad_server_version: "0.6.0"
nomad_server_archive_sum: "fcf108046164cfeda84eab1c3047e36ad59d239b66e6b2f013e6c93064bc6313"

nomad_server_url_prefix: "https://releases.hashicorp.com/nomad/{{ nomad_server_version }}"
nomad_server_archive_name: "nomad_{{ nomad_server_version }}_linux_amd64.zip"
nomad_server_archive_dest: "{{ nomad_server_cache_dir }}/{{ nomad_server_archive_name }}"
nomad_server_archive_url: "{{ nomad_server_url_prefix }}/{{ nomad_server_archive_name }}"

nomad_server_data_dir: "/var/lib/nomad"
nomad_server_config_dir: "/etc/nomad.d"

nomad_server_dc_name: "dc1"

nomad_server_user_name: "nomad"
nomad_server_user_id: "802"

nomad_server_network_interface: eth0