---
- hosts: all
  become: yes
  tags:
    - agents
  roles:
    - consul-agent
    - prometheus-node

- hosts: monitor
  become: yes
  roles:
    - prometheus-master
    - grafana

- hosts: nomad-servers-bootstrap
  become: yes
  roles:
    - nomad-server
    - prometheus-statsd

- hosts: nomad-servers-bootstrap
  become: yes
  tags:
    - statsd
  roles:
    - prometheus-statsd

- hosts: nomad-workers
  become: yes
  tags:
    - nomad
  roles:
    - nomad-worker
    - prometheus-statsd
    - docker
