---
- hosts: all
  become: yes
  tags:
    - agents
    - traefik
  roles:
    - consul-agent
    - prometheus-node

- hosts: monitor
  become: yes
  roles:
    - prometheus-master

- hosts: monitor
  become: yes
  tags:
    - monitor
  roles:
    - grafana

- hosts: nomad-servers-bootstrap
  become: yes
  roles:
    - nomad-server
    - prometheus-statsd

- hosts: nomad-workers
  become: yes
  tags:
    - nomad
  roles:
    - nomad-worker
    - prometheus-statsd
    - docker

- hosts: entry
  become: yes
  tags:
    - traefik
    - monitor
  roles:
    - traefik
