---
- hosts: localhost
  become: no
  gather_facts: no

  pre_tasks:
    - assert:
        that:
          - layer_name is defined
        msg: >-
          Please define 'layer_name' variable.

  tasks:
    - name: terraform destroy
      shell: >-
        terraform get -update
        &&
        terraform destroy {{ common_tf_vars }} -force
      args:
        chdir: "{{ terraform_current_layer }}"

