---
vault_version: "0.8.3"
vault_archive_sum: "a3b687904cd1151e7c7b1a3d016c93177b33f4f9ce5254e1d4f060fca2ac2626"

vault_url_prefix: "https://releases.hashicorp.com/vault/{{ vault_version }}"
vault_archive_name: "vault_{{ vault_version }}_linux_amd64.zip"
vault_archive_dest: "{{ vault_cache_dir }}/{{ vault_archive_name }}"
vault_archive_url: "{{ vault_url_prefix }}/{{ vault_archive_name }}"

vault_config_file: "/etc/vault.conf"

vault_log_dest: "/var/log/vault.log"
vault_user_name: "vault"
vault_user_id: "803"
vault_cache_dir: "/var/cache/run"

vault_cluster_name: "dc1"