---
consul_http_port: 8500

consul_binary_basedir: "/usr/local/bin"

consul_ui_service_name: consul-ui

consul_binary_path: "{{ consul_binary_basedir }}/consul"

consul_ui_traefik_backend_server: >-
  traefik.backends.{{ consul_ui_service_name }}.servers.{{ inventory_hostname }}
